### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by jacobp100** [bmeck/UnambiguousJavaScriptGrammar#16]
The other proposals enabled you to ship a transpiled version of the code using commonjs for older Node versions, whilst still shipping ES6 imports/exports for newer versions. How will this proposal enable you to support both older and newer Node environments without compromising the code run on each?

**Comment by jdalton** [comment]
Folks wanting compatibility would just continue to publish transpiled packages as the do today. When they're ready to take the leap then they'd switch to non-transpiled ES module use.

**Comment by ljharb** [comment]
It's a pretty strong requirement to be able to publish a package with native ES module code, transparently alongside (presumably transpiled) CJS code - are you implying that this wouldn't be possible?

**Comment by jdalton** [comment]
The current workflow of publishing transpiled ES to CJS code works and will continue to work.
Folks wanting back compat will continue transpiling.

**Comment by jacobp100** [comment]
Some bundling systems may have an issue with this solution.

**Comment by jdalton** [comment]
> Some bundling systems may have an issue with this solution.

It's how things are currently done, today.

**Comment by ljharb** [comment]
Any module detection proposal that does not allow _native_ - not transpiled - ES modules alongside CJS code is a nonstarter.

If I'm misunderstanding, and you simply mean that "the CJS will be produced from the native ES module code, via transpiling" then we're on the same page.

**Comment by jdalton** [comment]
To clarify I mean today folks who are using ES modules currently develop with ES modules and then publish as CJS through transpilation. So the source packaged is CJS. That is what I mean when I refer to the "current workflow".

**Comment by ljharb** [comment]
Sure! I believe the OP's question is: with your proposal, would I be able to use the current workflow, but ship the ES module code _alongside_ the transpiled CJS code, and have old nodes use the CJS transparently, and have new news use the native ES module code transparently?

**Comment by bmeck** [comment]
@ljharb that got stripped out as extra noise (since this got some confusion on TC39 side: https://github.com/tc39/agendas/pull/194 ). We will need to discuss `modules.root` separate from this (new EP), but I would heavily encourage such side-by side shipping work whenever Modules first land. There is also some efforts to discuss binary fat pkgs that needs to be revived and we got thrown for a loop after reading https://twitter.com/awbjs/status/744701901560651777 , which means we may end up with even more things to think about if we have to ship a newer parse goal down the road.

**Comment by ljharb** [comment]
I totally agree that nothing about module detection belongs in this proposal.

It's fine to be cautious, but I wouldn't hold your breath for another parsing goal to ever achieve committee consensus.

The thing I'm claiming is important is that the instant `import`/`export` functions natively in node, so-called "fat" packages must be possible.

**Comment by jdalton** [comment]
Transpiled code is not 100% compliant which can lead to inconsistencies in side-by-side scenarios. In addition, during the CTC meetings it was discovered that the `modules.root` feature had uses outside of ES modules, like pseudo private modules, which could be leveraged by CJS. Since it has merits on its own and can be seen as independent of the ES module proposal, `modules.root` was cut from this proposal.

Folks wanting older Node support can continue with their current workflow without worry of inconsistencies as all code is essentially transpiled CJS. No muss, no fuss.

**Comment by ljharb** [comment]
We don't need to debate this here, I suppose, since it's not part of this proposal. But no native module proposal for node should be considered imo unless everyone can have older node support in a package simultaneously with having native module support.

**Comment by jdalton** [comment]
Yep. Doubling the size of a package, introducing hard to nail down inconsistencies, and complicating module path resolution are things to hammer on in separate proposal for sure :wrench: :hammer:.
