### ISSUE TITLE
Is this proposal rejected from TC39 or not?

### ISSUE THREAD

**Issue by saschanaz** [bmeck/UnambiguousJavaScriptGrammar#22]
I'd like to see this on https://github.com/tc39/proposals/ but no list include this. Is this still stage 1 or rejected?

**Comment by ljharb** [comment]
See https://github.com/rwaldron/tc39-notes/blob/c2aaad7ef4a348b7ab019cca9f19b07f7484478a/es7/2017-01/jan-25.md#conclusionresolution-1 - it did not receive consensus for stage 1, so that makes it either stage 0, or rejected. See https://github.com/tc39/proposals/blob/master/inactive-proposals.md where it appears as rejected under "Proposed Grammar change to ES Modules".

**Comment by saschanaz** [comment]
@ljharb Per 2016-11 note https://github.com/rwaldron/tc39-notes/blob/be8c2af6d6dcfc9630e00ea15bbabf1a415245cb/es7/2016-11/dec-1.md#conclusionresolution-3 this is accepted as stage 1, though.

**Comment by ljharb** [comment]
I updated my comment - in January 2017, it failed to achieve consensus to move on, and was considered rejected.

**Comment by saschanaz** [comment]
>where it appears as rejected under "Proposed Grammar change to ES Modules".

Ah, couldn't find it because I was just searching "unambiguous".

Thanks for clarification 👍
