### ISSUE TITLE
Clarify packaged webapps impact

### ISSUE THREAD

**Issue by rvagg** [bmeck/UnambiguousJavaScriptGrammar#4]
Under **External Impact** it says:

> Microsoft packaged web apps can benefit from unambiguous Script and Module goals. At the moment there is no way to detect the intended goal of JavaScript files so bytecode caches are generated for the Script goal and discarded if ES modules are encountered.

Can you expand this section a little to describe why they are unambiguous for packaged webapps for those of us with little knowledge of how they work? What are the ways in which .js files are included where they don't come via a `<script>` tag? Just a bit of background might help reinforce this point because it's non-obvious to a complete outsider.

**Comment by jdalton** [comment]
While scripts do come in via the `<script>` tag when the app is run it's my understanding that the bytecode generation is done without running the app as part of its install. Because the app isn't running there's no context of each file's intended goal. \cc @AtOMiCNebula

**Comment by jdalton** [comment]
\cc @AtOMiCNebula

**Comment by AtOMiCNebula** [comment]
Yep, cached bytecode for HTML+JavaScript UWP apps is generated independently of the app being run.  We can't know ahead of time whether a `.js` file will be loaded with or without `type="module"`...maybe it'll even be loaded both ways.  So, until we have a good way to be smarter about bytecode caching, caches are only populated from parsing as common scripts.  One side-effect of this, however, is that we must ignore cached bytecode if we find any while trying to load a module script, since a script that parsed successfully as common script may not parse as a module script (due to module scripts' implicit `"use strict"`).

This is, of course, largely just a thought experiment for now...HTML+JavaScript UWP apps don't have a way to utilize ES6 Modules yet, as it's an experimental feature in the browser only (on current Windows Insider builds).  But, we know it's an issue we have to solve. 😄
