### ISSUE TITLE
Remove or minimize module detection text

### ISSUE THREAD

**Issue by ljharb** [bmeck/UnambiguousJavaScriptGrammar#8]
This change does not, in one fell swoop, resolve the non-ecma-related "module detection" debate.

While this change definitely alters the situation slightly, which might indeed make module detection proposals suddenly become viable, in reality this is a change that's defensible, and imo good, entirely in isolation from "module detection".

I think there's been a lot of misunderstanding from this document by those who see it as part of the "node concern" of "module detection" (let's not respond to that reaction for the sake of this issue please). I think it would be very clarifying if this proposal was primarily presented as "this removes a mostly useless ambiguous case from the Module parsing goal, which has the additional benefit of making no "source text" parse as both a Script or a Module".

Thoughts?

**Comment by ljharb** [comment]
Specifically, for example, [this section](https://github.com/bmeck/UnambiguousJavaScriptGrammar#operation) imo does not belong in this proposal other than as an explicitly marked explanatory use case - and the [TLDRs](https://github.com/bmeck/UnambiguousJavaScriptGrammar#tldr) are a bit more grandiose than simply this ecma proposal.

**Comment by jdalton** [comment]
I'm not sure when you viewed the section in question. It was pretty large at one point.
I've since reduce the section.

Yap. With this proposal I'm opting for simple over complex. Even if that means scoping things down.
The TL;DRs were there to help counter the knee-jerk of a multiple parse approach.

I'll work with @bmeck to make a more focused ECMAScript proposal.

**Comment by jdalton** [comment]
I'll work with @bmeck to make a more focused ECMAScript proposal.
